name: GIPHY generator

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  issue_comment:
    types: [opened, edited]

jobs:
  giphy-generator:
    runs-on: ubuntu-latest

    steps:
      - name: GIPHY Generator
        uses: IAmHughes/giphy-generator@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
        with:
          # The content rating used to filter results from the GIF search. Default: `g`
          rating: 'g'
          # The default language that the search query is in. Default: `en` for English
          lang: 'en'
          
